name: component
description: A new Flutter package project.
version: 0.0.1
author: "KodingWorks"
homepage: "https://kodingworks.io"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  preferences:
    path: ../preferences
  dependencies:
    path: ../dependencies
  l10n:
    path: ../l10n
  shimmer: ^1.1.2
  flutter_inappwebview: ^4.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.0

flutter:
