name: flutter_modular
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  core:
    path: shared/core
  dependencies:
    path: shared/dependencies
  l10n:
    path: shared/l10n
  auth:
    path: features/auth
  home:
    path: features/home
  settings:
    path: features/settings
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_flavorizr: ^1.0.3
  effective_dart: ^1.3.0
  flutter_native_splash: ^0.2.11

flutter:
  uses-material-design: true
  
  assets:
    - assets/cfg/
    - assets/images/
    - assets/images/bitmap/
    - assets/images/icons/
    - assets/images/illustration/
    
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "launcher/ic_launcher.png"
  adaptive_icon_background: "#E67442"
  adaptive_icon_foreground: "launcher/ic_foreground.png"
  image_path_ios: "launcher/ic_launcher.png"

flutter_native_splash:
  image: launcher/logo_splash.png
  color: "ffffff"
  android_disable_fullscreen: true