name: dependencies
description: A new Flutter package project.
version: 0.0.1
author: "KodingWorks"
homepage: "https://kodingworks.io/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  dio: ^3.0.10
  equatable: ^1.2.6
  flutter_bloc: ^6.1.2
  formz: ^0.3.2
  get_it: ^5.0.6
  hive: ^1.4.4+1
  image_picker: ^0.6.7+22
  path_provider: ^1.6.27
  intl: ^0.16.1
  carousel_slider: ^2.3.4
  rxdart: ^0.25.0
  url_launcher: ^5.7.10
  package_info: ^0.4.3+4
  dio_firebase_performance: ^0.3.0

  # firebase
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_messaging: ^8.0.0-dev.14
  firebase_performance: ^0.5.0+1
  firebase_remote_config: ^0.6.0
  google_sign_in: ^4.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
