name: core
description: A new Flutter package project.
version: 0.0.1
author: "KodingWorks"
homepage: "https://kodingworks.io/"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../dependencies
  l10n:
    path: ../l10n
  component:
    path: ../component

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.0
  intl_utils: ^1.9.0
  mockito: ^4.1.3

flutter:
